dist: trusty

sudo: false

language: php

php:
    - 5.6
    - 7.0

env:
    global:
        - secure: "I4hhqjsQyJ6cU4+EGaZUSrtGE9A1UgQFlYZb/qfIJVedjGuet4fyIxGTEP5pmKkR3AIBVGSo4VluMOUxcyYYc5DOaBn7Y2iH8Jbgf2rZp/MzeNtyAM0TbLTfmrpFp6exgiDfEJlRNNqzZ6Hz+MqeUd/DRuZ3TBW5Hcy2LfIzSiB6dtq8apVkRsI1hjwPGMfMqCuie5AdoAHkYDjUAc49mLS2ytfPwMBtpG6dQXQ3uL5nyT+CqdEW3UL9c8jTSZtTiK45WDQBxplvrXYK4rfnXs5u4GdUBVaAkwgmfIAg4up4db1rW5BRH2D7WYyi3SRNRYqVpW3WHqCQzqz0C6qICiknnIrEpa7mBVRFy65gokVzIdnPZKUypuV+vsD4+FbWB6R9S4Nu9idifPh3rGGuDFD7qLmCik6fV61iMfmpoGqob4/MzeUQ5e+/II8gTRRdyzRFxCRsJ70L2dqSthxg3vFXpdDXv6NEbQKpCr4Nu0yAGVgMNrCfXgTXd17ix+/ba8w38jTgu/2tBNvQXHQaPPXWq+uVVTrNCwWqo+76p6toOu4RcZnrf7ISs4Q+hyO2AG6d3OkmnunPMJ2KYv0zqmKW6GT2y+ksPFLzJ7fEy9X0rdJ0Jc0N9EVWuHhxn6gHjseVN3f5dLHUR/iQRmkrr3DGx7gQ6IpXpL1tjOzxoo8="
        - secure: "cSG1UmlMOcJAcIrG7XW1Nz4EOu+okFgjC8lJT3o64aQIhW+4Ulg+odm8IL6ImV0tvqjk9pe4OP++gsFIwwZfLHCNPKsv9T2hm/XJF207lQNddRbLxvZDXiE9AbvvonkUHGT502MD4bQRywQqL/tOu1QCQKJVr+g0ZPY41mp+pn4q3ewyUBqtrrH+OKzAz2hhE1LW0zEMO0mrPr2z2Pfvl1A95wCY3zV9SCTdiiHJRp89oheTaPAyDiPC8cuJfGAu7gPC6XW5GyRT4CHjGtS5IiZt1u8in8f76MsYjJsTBQ/SOBLJoAhNIPIi5UToZtJ3xDenXplLJXFI+NVyvKVzAbQDbyIr9td1PPGlNrC+uezQ0+dBuCMGnRl/69FonXNUX9gYtf25ApSml5vKuujdGNHfICMccaM/abCkEciXYzOpmHojnOuCsXBy9Slm7SBgptQ5Pvz71qRG23IvIj0AK4I/AluwQESUCSt2xz6lzuP2GHV9RAERyKFA8ymp2ct0DQeu+MHP7Hh+FMf4k/pU8/3mAmPgPXLEbIzFOyB6K3pQ4P2cGT9w/7T6yqFTiIo9wQBUZG6W+bItNZk+lJizhsqO43YQRtY8IiTYqLRsGHw1e7233/6oL+PG5DOgif47lmUzGAfDixCMfptG0mTqj1sN+G24O47qDoxrfDjUrl8="
    matrix:
        - TEST_SUITE=unit
cache:
    directories:
        - $HOME/.composer/cache

install:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then echo '{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}' > auth.json; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then composer install --prefer-dist; fi"

script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi"

after_script:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/coveralls; fi"

cache:
    directories:
        - $HOME/.composer/cache

addons:
    apt:
        packages:
            - graphviz
    code_climate:
        repo_token: 2ab91604eedc0a66d2033644ab9f4ce603bd6d6571c1fc24745b470a6369f850